on:
  push:
    branches:
    - main
jobs:
  export:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
      
    - name: Godot Export
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_32.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
        relative_project_path: ./MartianMike
        archive_output: true
        cache: true
        
    - uses: actions/upload-artifact@v4
      name: Upload raw
      with:
        name: Raw Outputs
        path: ${{ steps.export.outputs.build_directory }}/*
        if-no-files-found: error
        
    - uses: actions/upload-artifact@v4
      name: Upload archives
      with:
        name: Archives
        path: ${{ steps.export.outputs.archive_directory }}/*
        if-no-files-found: error
        
